# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BEG5hghrrbopj4C-YhTOW8o7FoWhpQq6
"""

# Name - Mohit Mathur
# Roll No.- G25AIT1092


!pip install ucimlrepo
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from ucimlrepo import fetch_ucirepo


wine = fetch_ucirepo(id=186)
X = wine.data.features
y = wine.data.targets['quality'].to_numpy()

y_binary = np.where(y > 5, 1, 0)
X = X.to_numpy()

feature_names = wine.data.features.columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(
    X, y_binary, test_size=0.2, random_state=42, stratify=y_binary
)

class Node:
    def __init__(self, impurity, num_samples, num_samples_per_class, predicted_class):
        self.impurity = impurity
        self.num_samples = num_samples
        self.num_samples_per_class = num_samples_per_class
        self.predicted_class = predicted_class
        self.feature_index = None
        self.threshold = None
        self.left = None
        self.right = None


class DecisionTreeClassifierScratch:
    def __init__(self, max_depth=None, min_samples_split=2, criterion="gini", n_features=None):
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.criterion = criterion
        self.n_features = n_features
        self.n_classes = None
        self.tree_ = None

    def fit(self, X, y):
        self.n_classes = len(set(y))
        self.n_features = X.shape[1] if self.n_features is None else min(self.n_features, X.shape[1])
        self.tree_ = self._grow_tree(X, y)

    def predict(self, X):
        return [self._predict(inputs) for inputs in X]

    def _gini(self, y):
        m = len(y)
        return 1.0 - sum((np.sum(y == c) / m) ** 2 for c in set(y))

    def _impurity(self, y):
        return self._gini(y)

    def _information_gain(self, y, left_mask, right_mask):
        m = len(y)
        parent_impurity = self._impurity(y)
        left_impurity = self._impurity(y[left_mask])
        right_impurity = self._impurity(y[right_mask])
        n_left = np.sum(left_mask)
        n_right = np.sum(right_mask)
        weighted_avg = (n_left / m) * left_impurity + (n_right / m) * right_impurity
        return parent_impurity - weighted_avg

    def _best_split(self, X, y):
        m, n = X.shape
        if m < self.min_samples_split:
            return None, None

        features = np.random.choice(n, self.n_features, replace=False)
        best_gain, best_idx, best_thr = 0, None, None

        for idx in features:
            thresholds, classes = zip(*sorted(zip(X[:, idx], y)))
            thresholds, classes = np.array(thresholds), np.array(classes)

            for i in range(1, m):
                if classes[i] == classes[i - 1]:
                    continue
                thr = (thresholds[i] + thresholds[i - 1]) / 2
                left_mask = X[:, idx] <= thr
                right_mask = X[:, idx] > thr
                gain = self._information_gain(y, left_mask, right_mask)
                if gain > best_gain:
                    best_gain, best_idx, best_thr = gain, idx, thr

        return best_idx, best_thr

    def _grow_tree(self, X, y, depth=0):
        num_samples_per_class = [np.sum(y == i) for i in range(self.n_classes)]
        predicted_class = np.argmax(num_samples_per_class)
        node = Node(self._impurity(y), y.size, num_samples_per_class, predicted_class)

        if depth < (self.max_depth or np.inf) and y.size >= self.min_samples_split and node.impurity > 0:
            idx, thr = self._best_split(X, y)
            if idx is not None:
                indices_left = X[:, idx] <= thr
                X_left, y_left = X[indices_left], y[indices_left]
                X_right, y_right = X[~indices_left], y[~indices_left]
                node.feature_index = idx
                node.threshold = thr
                node.left = self._grow_tree(X_left, y_left, depth + 1)
                node.right = self._grow_tree(X_right, y_right, depth + 1)
        return node

    def _predict(self, inputs):
        node = self.tree_
        while node.left:
            if inputs[node.feature_index] <= node.threshold:
                node = node.left
            else:
                node = node.right
        return node.predicted_class


class RandomForestClassifierScratch:
    def __init__(self, n_trees=10, max_depth=None, min_samples_split=2, n_features=None):
        self.n_trees = n_trees
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.n_features = n_features
        self.trees = []

    def _bootstrap_sample(self, X, y):
        m = X.shape[0]
        idxs = np.random.choice(m, m, replace=True)
        return X[idxs], y[idxs]

    def fit(self, X, y):
        self.trees = []
        for _ in range(self.n_trees):
            X_samp, y_samp = self._bootstrap_sample(X, y)
            tree = DecisionTreeClassifierScratch(
                max_depth=self.max_depth,
                min_samples_split=self.min_samples_split,
                n_features=self.n_features
            )
            tree.fit(X_samp, y_samp)
            self.trees.append(tree)

    def predict(self, X):
        tree_preds = np.array([tree.predict(X) for tree in self.trees])
        tree_preds = np.swapaxes(tree_preds, 0, 1)
        y_pred = [Counter(preds).most_common(1)[0][0] for preds in tree_preds]
        return np.array(y_pred)

    def feature_importances(self, X, y):
        importances = np.zeros(X.shape[1])
        for tree in self.trees:
            self._compute_importance(tree.tree_, importances, X, y)
        return importances / len(self.trees)

    def _compute_importance(self, node, importances, X, y):
        if node is None or node.left is None or node.right is None:
            return
        left_mask = X[:, node.feature_index] <= node.threshold
        right_mask = X[:, node.feature_index] > node.threshold
        gain = self._impurity_gain(y, left_mask, right_mask)
        importances[node.feature_index] += gain
        self._compute_importance(node.left, importances, X[left_mask], y[left_mask])
        self._compute_importance(node.right, importances, X[right_mask], y[right_mask])

    def _impurity_gain(self, y, left_mask, right_mask):
        m = len(y)
        def gini(y): return 1 - sum((np.sum(y == c)/len(y))**2 for c in np.unique(y))
        parent = gini(y)
        left = gini(y[left_mask])
        right = gini(y[right_mask])
        n_left = np.sum(left_mask)
        n_right = np.sum(right_mask)
        return parent - (n_left/m)*left - (n_right/m)*right


rf = RandomForestClassifierScratch(n_trees=50, max_depth=10, n_features=int(np.sqrt(X.shape[1])))
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

dt = DecisionTreeClassifierScratch(max_depth=None)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

def eval_metrics(y_true, y_pred):
    return {
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred),
        'Recall': recall_score(y_true, y_pred),
        'F1-Score': f1_score(y_true, y_pred)
    }

rf_metrics = eval_metrics(y_test, y_pred_rf)
dt_metrics = eval_metrics(y_test, y_pred_dt)

print("\n=== Performance Comparison ===")
results_df = pd.DataFrame([rf_metrics, dt_metrics], index=['Random Forest', 'Decision Tree'])
print(results_df)

tree_counts = [1, 5, 10, 25, 50, 100]
acc_scores = []

for n in tree_counts:
    rf_temp = RandomForestClassifierScratch(n_trees=n, max_depth=10, n_features=int(np.sqrt(X.shape[1])))
    rf_temp.fit(X_train, y_train)
    y_pred_temp = rf_temp.predict(X_test)
    acc_scores.append(accuracy_score(y_test, y_pred_temp))
    print(f"Accuracy for {n} trees: {acc_scores[-1]}")

plt.figure(figsize=(8,5))
plt.plot(tree_counts, acc_scores, marker='o')
plt.xlabel("Number of Trees (n_trees)")
plt.ylabel("Test Accuracy")
plt.title("Accuracy vs Number of Trees in Random Forest")
plt.grid(True)
plt.show()

importances = rf.feature_importances(X_train, y_train)
sorted_idx = np.argsort(importances)[::-1]
plt.figure(figsize=(8,5))
plt.bar(range(len(importances)), importances[sorted_idx])
plt.xticks(range(len(importances)), np.array(feature_names)[sorted_idx], rotation=45, ha='right')
plt.title("Feature Importance (Random Forest)")
plt.tight_layout()
plt.show()